# test_latent_opt/params.yaml
esm:
  model_name: esm3_sm_open_v1
  embeddings: esm # one of structure_vae or esm

latent_model:
  module: PoolLinear
  lr: 0.01
  optimizer: adam
  early_stopping_patience: 5
  early_stopping_tolerance: 0.01
  epochs: 100
  dropout: 0.1


optimization:
  proteins_to_optimize: []
  num_steps_per_trajectory: 100
  num_trajectories_per_protein: 10
  lr: 0.1
  optimizer: adam


